### ISSUE TITLE
ClassCastException invoking DB.getCollections

### ISSUE THREAD

**Issue by ajermakovics** [jankotek/JDBM3#15]
Using Alpha2

```
DB db = new DBMaker("db").build();
db.createTreeMap("treemap");
db.getCollections();
```

**Comment by jankotek** [comment]
Fixed in git

**Comment by jkauzlar** [comment]
I'm still getting the same issue with DB#deleteCollection:

Caused by: java.lang.ClassCastException: net.kotek.jdbm.HTree cannot be cast to java.util.Collection
 at net.kotek.jdbm.DBStore.deleteCollection (DBStore.java:401)
    net.kotek.jdbm.DBCache.deleteCollection (DBCache.java:726)

This is from the repo source I downloaded & built about 10 minutes ago.

**Comment by jankotek** [comment]
Fixed, thanks

**Comment by jkauzlar** [comment]
Hi, this has crept back into head again with getCollections. I haven't retested deleteCollection yet.. thanks
